name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: pip install buildozer
      - run: buildozer init
      - run: buildozer android debug deploy
      - uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
